name: {{cookiecutter.project_short_name}}
channels:
  - conda-forge
dependencies:
  - python=3.6
  - numpy=1.13.3
  - pandas=0.20.3
  - matplotlib=2.1.0
  - seaborn=0.8.1
  - pandoc=1.19.2.1
  - pytest=3.2.3
  - click=6.7
  - pip:
      - pytest-pythonpath # adds the root path "./" to PYTHONPATH
      - pandoc-tablenos
      - pandoc-fignos
      - pantable
